# Welcome to Jekyll!
#

# Site settings
title: Miquel Esteva
description: |
  Personal Portfolio  
  by Miquel Esteva
owner: Miquel Esteva
first_published: 2018
email: miquel.esteva9@gmail.com
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://miquelesteva.github.io/"
social:
  twitter: https://twitter.com/miquel403
  github: https://github.com/miquelesteva
  facebook-official: https://facebook.com/Miquel Esteva
  google-plus-square: https://plus.google.com/u/0/114380418605586336407
  email: miquel.esteva9@gmail.com

