# Welcome to Jekyll!
#

# Site settings
title: Portofolio de Miquel
description: |
  Personal Portfolio  
  by Miquel Esteva
owner: Miquel Esteva
first_published: 2018
email: miquel.esteva9@gmail.com
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://miquelesteva.github.io/"
social:
  twitter: https://twitter.com/miquel403
  github: https://github.com/miquelesteva
#  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/Miquel Esteva
  google-plus-square: https://plus.google.com/u/0/+<username>
  email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
